logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.postgresql: INFO
    org.springframework.data: INFO

spring:
  mvc:
    log-request-details: true

  # Database
  datasource:
    url: "jdbc:postgresql://postgres:5432/tickets?stringtype=unspecified"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Flyway
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:/db/migration, classpath:/db/test_data

  # JPA properties
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  redis:
    host: redis
    port: 6379

    # Server configuration
server:
  port: 8081 #set your port

