apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: microservices-user:latest
          ports:
            - containerPort: 8083
          env:
            - name: spring.datasource.url
              value: "jdbc:postgresql://postgres:5432/tickets"
            - name: spring.datasource.username
              value: postgres
            - name: spring.datasource.password
              value: postgres
            - name: spring.redis.host
              value: redis
            - name: spring.redis.port
              value: "6379"
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: LoadBalancer   # Specify the service type as LoadBalancer
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083